// Generated by `cfdo create`.
//
// The __CFDO_ADMIN__ routes are what `cfdo backup` and `cfdo restore` talk to.
// Cloudflare has no server-side API that can read Durable Object storage, so
// the export/import has to run inside the object itself. Keep these routes,
// keep them behind the CFDO_SECRET binding, and write your own logic below.

import { DurableObject } from "cloudflare:workers";

const ADMIN_PREFIX = "/__cfdo/";
const PAGE = 1000;

// Cloudflare's object-listing API is lagging and incomplete for SQLite-backed
// namespaces — objects can be missing from it long after they hold data — so
// the worker keeps its own index of the names it has routed to, in one
// well-known object.
const INDEX_NAME = "__cfdo_index";

export class Guestbook extends DurableObject {
  async fetch(request) {
    const url = new URL(request.url);
    if (url.pathname.startsWith(ADMIN_PREFIX)) {
      return this.admin(request, url);
    }
    return this.app(request, url);
  }

  // ------------------------------------------------------------ your code
  // One guestbook room per object. All state lives in this object's own
  // SQLite database, so reads need no coordination and writes are serialised
  // by the object itself — no locking, no race between two visitors posting.
  constructor(ctx, env) {
    super(ctx, env);
    this.ctx.storage.sql.exec(
      "CREATE TABLE IF NOT EXISTS messages (" +
      "  id INTEGER PRIMARY KEY AUTOINCREMENT," +
      "  author TEXT NOT NULL," +
      "  body TEXT NOT NULL," +
      "  created_at TEXT NOT NULL)"
    );
  }

  async app(request, url) {
    const room = url.searchParams.get("room") ?? "lobby";

    if (request.method === "POST") {
      const form = await request.formData();
      const author = (form.get("author") ?? "").toString().trim().slice(0, 40) || "anonymous";
      const body = (form.get("body") ?? "").toString().trim().slice(0, 500);
      if (body) {
        this.ctx.storage.sql.exec(
          "INSERT INTO messages (author, body, created_at) VALUES (?, ?, ?)",
          author, body, new Date().toISOString()
        );
      }
      // redirect so a refresh does not repost
      return new Response(null, { status: 303, headers: { Location: url.pathname } });
    }

    const rows = [...this.ctx.storage.sql.exec(
      "SELECT author, body, created_at FROM messages ORDER BY id DESC LIMIT 100"
    )];
    const total = [...this.ctx.storage.sql.exec("SELECT COUNT(*) AS n FROM messages")][0].n;

    return new Response(renderPage(room, rows, total), {
      headers: { "content-type": "text/html; charset=utf-8", "cache-control": "no-store" },
    });
  }

  // ------------------------------------------------------------ cfdo admin
  async admin(request, url) {
    const op = url.pathname.slice(ADMIN_PREFIX.length);
    if (op === "export" && request.method === "GET") {
      return Response.json(await this.exportAll());
    }
    if (op === "register" && request.method === "POST") {
      const { name, id } = await request.json();
      await this.ctx.storage.put("n:" + name, id);
      return Response.json({ ok: true });
    }
    if (op === "list" && request.method === "GET") {
      const entries = [];
      let startAfter;
      for (;;) {
        const opts = { prefix: "n:", limit: PAGE };
        if (startAfter !== undefined) opts.startAfter = startAfter;
        const page = await this.ctx.storage.list(opts);
        if (page.size === 0) break;
        for (const [k, id] of page) {
          entries.push({ name: k.slice(2), id });
          startAfter = k;
        }
        if (page.size < PAGE) break;
      }
      return Response.json({ objects: entries });
    }
    if (op === "import" && request.method === "POST") {
      const mode = url.searchParams.get("mode") === "replace" ? "replace" : "merge";
      const body = await request.json();
      return Response.json(await this.importAll(body, mode));
    }
    return new Response("not found", { status: 404 });
  }

  async exportAll() {
    const out = { format: 1, class: "Guestbook", exported_at: new Date().toISOString(), kv: [] };

    let startAfter;
    for (;;) {
      const opts = { limit: PAGE };
      if (startAfter !== undefined) opts.startAfter = startAfter;
      const page = await this.ctx.storage.list(opts);
      if (page.size === 0) break;
      for (const [k, v] of page) {
        out.kv.push([k, encode(v)]);
        startAfter = k;
      }
      if (page.size < PAGE) break;
    }

    const alarm = await this.ctx.storage.getAlarm();
    if (alarm !== null) out.alarm = alarm;

    const sql = this.ctx.storage.sql;
    if (sql) {
      out.sql = [];
      const tables = [...sql.exec(
        "SELECT name, sql FROM sqlite_master WHERE type='table' " +
        "AND name NOT LIKE 'sqlite_%' AND name NOT LIKE '_cf_%'"
      )];
      for (const t of tables) {
        const rows = [...sql.exec('SELECT * FROM "' + t.name.replace(/"/g, '""') + '"')];
        out.sql.push({
          name: t.name,
          schema: t.sql,
          rows: rows.map((r) => {
            const o = {};
            for (const k of Object.keys(r)) o[k] = encode(r[k]);
            return o;
          }),
        });
      }
    }
    return out;
  }

  async importAll(body, mode) {
    if (!body || body.format !== 1) {
      return { ok: false, error: "unsupported backup format" };
    }
    const sql = this.ctx.storage.sql;

    if (mode === "replace") {
      if (sql && Array.isArray(body.sql)) {
        for (const t of body.sql) {
          sql.exec('DROP TABLE IF EXISTS "' + t.name.replace(/"/g, '""') + '"');
        }
      }
      await this.ctx.storage.deleteAll();
    }

    let kv = 0;
    const entries = body.kv ?? [];
    for (let i = 0; i < entries.length; i += 128) {
      const chunk = {};
      for (const [k, v] of entries.slice(i, i + 128)) chunk[k] = decode(v);
      await this.ctx.storage.put(chunk);
      kv += Object.keys(chunk).length;
    }

    let rows = 0;
    if (sql && Array.isArray(body.sql)) {
      for (const t of body.sql) {
        if (t.schema) {
          sql.exec(t.schema.replace(/^CREATE TABLE /i, "CREATE TABLE IF NOT EXISTS "));
        }
        for (const row of t.rows ?? []) {
          const cols = Object.keys(row);
          if (cols.length === 0) continue;
          const quoted = cols.map((c) => '"' + c.replace(/"/g, '""') + '"').join(", ");
          const marks = cols.map(() => "?").join(", ");
          sql.exec(
            'INSERT OR REPLACE INTO "' + t.name.replace(/"/g, '""') + '" (' + quoted + ") VALUES (" + marks + ")",
            ...cols.map((c) => decode(row[c]))
          );
          rows++;
        }
      }
    }

    if (typeof body.alarm === "number") await this.ctx.storage.setAlarm(body.alarm);
    return { ok: true, mode, kv, rows };
  }
}

// Values in DO storage are structured-clonable, which JSON is not. Tag the
// types JSON would otherwise lose so a round trip is lossless.
function encode(v) {
  if (v === undefined) return { $t: "undefined" };
  if (v === null || typeof v === "boolean" || typeof v === "number" || typeof v === "string") return v;
  if (typeof v === "bigint") return { $t: "bigint", v: v.toString() };
  if (v instanceof Date) return { $t: "date", v: v.toISOString() };
  if (v instanceof ArrayBuffer) return { $t: "bytes", v: b64encode(new Uint8Array(v)) };
  if (ArrayBuffer.isView(v)) {
    return { $t: "view", k: v.constructor.name, v: b64encode(new Uint8Array(v.buffer, v.byteOffset, v.byteLength)) };
  }
  if (v instanceof Map) return { $t: "map", v: [...v].map(([k, x]) => [encode(k), encode(x)]) };
  if (v instanceof Set) return { $t: "set", v: [...v].map(encode) };
  if (Array.isArray(v)) return { $t: "array", v: v.map(encode) };
  const o = {};
  for (const k of Object.keys(v)) o[k] = encode(v[k]);
  return { $t: "object", v: o };
}

function decode(v) {
  if (v === null || typeof v !== "object") return v;
  switch (v.$t) {
    case "undefined": return undefined;
    case "bigint": return BigInt(v.v);
    case "date": return new Date(v.v);
    case "bytes": return b64decode(v.v).buffer;
    case "view": {
      const bytes = b64decode(v.v);
      const Ctor = globalThis[v.k];
      if (!Ctor || Ctor === Uint8Array) return bytes;
      return new Ctor(bytes.buffer, 0, bytes.byteLength / (Ctor.BYTES_PER_ELEMENT ?? 1));
    }
    case "map": return new Map(v.v.map(([k, x]) => [decode(k), decode(x)]));
    case "set": return new Set(v.v.map(decode));
    case "array": return v.v.map(decode);
    case "object": {
      const o = {};
      for (const k of Object.keys(v.v)) o[k] = decode(v.v[k]);
      return o;
    }
    default: return v;
  }
}

function esc(v) {
  return String(v).replace(/[&<>"']/g, (c) =>
    ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]
  );
}

function renderPage(room, rows, total) {
  const items = rows.length === 0
    ? ""
    : rows.map((r) =>
        '<li><div class="meta"><strong>' + esc(r.author) + '</strong>' +
        '<time datetime="' + esc(r.created_at) + '">' + esc(r.created_at.replace("T", " ").slice(0, 19)) + ' UTC</time>' +
        '</div><p>' + esc(r.body) + '</p></li>'
      ).join("");

  return '<!doctype html><html lang="en"><head><meta charset="utf-8">' +
    '<meta name="viewport" content="width=device-width,initial-scale=1">' +
    '<title>' + esc(room) + ' · guestbook</title><style>' +
    ':root{color-scheme:light dark;--bg:#fbfbfa;--fg:#1a1a18;--mut:#6b6b66;--line:#e3e3df;--card:#fff;--accent:#b4531f}' +
    '@media (prefers-color-scheme:dark){:root{--bg:#141413;--fg:#f0efec;--mut:#9a9a93;--line:#2c2c2a;--card:#1c1c1a;--accent:#e08a52}}' +
    '*{box-sizing:border-box}body{margin:0;padding:32px 16px;background:var(--bg);color:var(--fg);' +
    'font:15px/1.6 ui-sans-serif,system-ui,-apple-system,Segoe UI,sans-serif}' +
    '.wrap{max-width:640px;margin:0 auto}h1{font-size:22px;margin:0 0 2px}' +
    '.sub{color:var(--mut);font-size:13px;margin:0 0 24px}' +
    'form{display:grid;gap:8px;background:var(--card);border:1px solid var(--line);border-radius:10px;padding:16px;margin-bottom:24px}' +
    'input,textarea{font:inherit;padding:9px 11px;border:1px solid var(--line);border-radius:7px;background:var(--bg);color:var(--fg);width:100%}' +
    'textarea{min-height:76px;resize:vertical}' +
    'button{font:inherit;font-weight:600;padding:9px 16px;border:0;border-radius:7px;background:var(--accent);color:#fff;cursor:pointer;justify-self:start}' +
    'ul{list-style:none;padding:0;margin:0;display:grid;gap:10px}' +
    'li{background:var(--card);border:1px solid var(--line);border-radius:10px;padding:13px 15px}' +
    '.meta{display:flex;justify-content:space-between;gap:12px;align-items:baseline;margin-bottom:4px}' +
    '.meta time{color:var(--mut);font-size:12px;font-variant-numeric:tabular-nums}' +
    'li p{margin:0;white-space:pre-wrap;overflow-wrap:anywhere}' +
    '.empty{color:var(--mut)}' +
    'footer{margin-top:28px;color:var(--mut);font-size:12px;border-top:1px solid var(--line);padding-top:14px}' +
    'code{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12px}' +
    '</style></head><body><div class="wrap">' +
    '<h1>' + esc(room) + '</h1>' +
    '<p class="sub">' + total + ' message' + (total === 1 ? "" : "s") + ' · served from a single Durable Object</p>' +
    '<form method="post"><input name="author" placeholder="your name" maxlength="40" autocomplete="off">' +
    '<textarea name="body" placeholder="leave a message" maxlength="500" required></textarea>' +
    '<button type="submit">Post</button></form>' +
    (items ? '<ul>' + items + '</ul>' : '<p class="empty">No messages yet. Be the first.</p>') +
    '<footer>Every room is its own object with its own SQLite database. ' +
    'Try <code>/r/anything</code> to create one.</footer>' +
    '</div></body></html>';
}

function b64encode(bytes) {
  let s = "";
  for (let i = 0; i < bytes.length; i += 0x8000) {
    s += String.fromCharCode.apply(null, bytes.subarray(i, i + 0x8000));
  }
  return btoa(s);
}

function b64decode(s) {
  const bin = atob(s);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

function authorized(request, env) {
  const got = request.headers.get("x-cfdo-secret") ?? "";
  const want = env.CFDO_SECRET ?? "";
  if (!want || got.length !== want.length) return false;
  let diff = 0;
  for (let i = 0; i < want.length; i++) diff |= got.charCodeAt(i) ^ want.charCodeAt(i);
  return diff === 0;
}

// Per-isolate memo so a hot path does not re-register a name it already has.
// Isolate recycling can cause a duplicate write, which is idempotent.
const registered = new Set();

function registerName(env, name, id) {
  if (name === INDEX_NAME || registered.has(name)) return null;
  registered.add(name);
  const idx = env.GUESTBOOK.get(env.GUESTBOOK.idFromName(INDEX_NAME));
  return idx.fetch("https://cfdo.invalid" + ADMIN_PREFIX + "register", {
    method: "POST",
    body: JSON.stringify({ name, id }),
  });
}

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);

    if (url.pathname.startsWith(ADMIN_PREFIX)) {
      if (!authorized(request, env)) {
        return new Response("unauthorized", { status: 401 });
      }
      if (url.pathname === ADMIN_PREFIX + "ping") {
        return Response.json({ ok: true, class: "Guestbook", binding: "GUESTBOOK", format: 1 });
      }
      if (url.pathname === ADMIN_PREFIX + "list") {
        const idx = env.GUESTBOOK.get(env.GUESTBOOK.idFromName(INDEX_NAME));
        return idx.fetch(request);
      }
      const idParam = url.searchParams.get("id");
      const nameParam = url.searchParams.get("name");
      let id;
      try {
        if (idParam) id = env.GUESTBOOK.idFromString(idParam);
        else if (nameParam) id = env.GUESTBOOK.idFromName(nameParam);
        else return new Response("missing id or name", { status: 400 });
      } catch (e) {
        return new Response("bad object id: " + e.message, { status: 400 });
      }
      return env.GUESTBOOK.get(id).fetch(request);
    }

    // ------------------------------------------------------------ your routing
    // /            -> the lobby
    // /r/<room>    -> one object per room name
    if (url.pathname === "/") {
      return Response.redirect(new URL("/r/lobby", url).toString(), 302);
    }
    const match = url.pathname.match(/^\/r\/([A-Za-z0-9_-]{1,32})$/);
    if (!match) {
      return new Response("not found", { status: 404 });
    }
    const name = match[1];
    url.searchParams.set("room", name);
    request = new Request(url, request);
    const id = env.GUESTBOOK.idFromName(name);

    // Keep this so `cfdo backup` can discover the object later. If you route
    // with newUniqueId() instead, record those ids yourself and feed them to
    // `cfdo backup -ids-file`.
    const reg = registerName(env, name, id.toString());
    if (reg) ctx.waitUntil(reg);

    return env.GUESTBOOK.get(id).fetch(request);
  },
};
